# 工作流名称
name: Assemble Ios Release

# 触发工作流程的事件
on:
  push:
    tags: [ v*, r*, i* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  APP_NAME: Taro
  VERSION_NUMBER: 1.7.0
  BUILD_NUMBER: 1.7.0.1
  BUILD_TYPE: release
  CODE_SIGN_IDENTITY: Apple Distribution

jobs:
  assemble:
    runs-on: macos-12
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=timestamp::$(TZ=Asia/Shanghai date +'%y%m%d%H%M')"
      - name: Checkout Project
        uses: actions/checkout@v2
#       - name: Cache node_modules Folder
#         uses: actions/cache@v2
#         with:
#           path: ${{ github.workspace }}/node_modules
#           key: ${{ runner.os }}-node_modules
#           restore-keys: ${{ runner.os }}-node_modules
#       - name: Get Yarn Cache Directory Path
#         id: yarn-cache-dir-path
#         run: echo "::set-output name=dir::$(yarn cache dir)"
#       - name: Cache Yarn
#         uses: actions/cache@v2
#         env:
#           cache-name: yarn-cache
#         with:
#           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-
#       - name: Install Dependencies
#         run: |
#           yarn
#       - name: Build 
#         run: |
#           yarn build:h5
      - name: ls 
        run: |
          ls
      - name: install hbuilderx
        run: |
          brew install --cask hbuilderx
      - name: hbuilderx ver
        run: /Applications/HBuilderX.app/Contents/MacOS/cli ver
      - name: hbuilderx open
        run: /Applications/HBuilderX.app/Contents/MacOS/cli open
      - name: project open
        run: /Applications/HBuilderX.app/Contents/MacOS/cli project open --path ./
      - name: hbuilderx login
        run: /Applications/HBuilderX.app/Contents/MacOS/cli user login --username --password
      - name: hbuilderx info
        run: /Applications/HBuilderX.app/Contents/MacOS/cli user info
     
      
